SPHINX_PROJECT_NAME=Motor Control Platform Software Guide
VERSION=2.0.0
DOXYGEN_DIRS =  ../../module_dsc_adc ../../module_dsc_blocks ../../module_dsc_comms
DOXYGEN_DIRS += ../../module_dsc_display ../../module_dsc_hall ../../module_dsc_qei
SOURCE_INCLUDE_DIRS=../../
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
