SPHINX_PROJECT_NAME=Motor Control
VERSION=2v0
DOXYGEN_DIRS =  ../../xmos_mc/module_dsc_adc ../../xmos_mc/module_dsc_blocks ../../xmos_mc/module_dsc_comms
DOXYGEN_DIRS += ../../xmos_mc/module_dsc_display ../../xmos_mc/module_dsc_hall ../../xmos_mc/module_dsc_pwm ../../xmos_mc/module_dsc_qei
SOURCE_INCLUDE_DIRS=../../xmos_mc
XDOC_DIR ?= ../../xdoc
include $(XDOC_DIR)/Makefile.inc
