# The top level directory of the application.

BASE_DIR = .

# The TARGET variable determines what target system the application is 
# compiled for. It either refers to an XN file in the source directories
# or a valid argument for the --target option when compiling.

TARGET = ...

# The build is made up of files found in all the directories listed
# in the SOURCE_DIRS variable. All directories are relative to the BASE_DIR.
# However, you can refer to directories in other modules by specifying:
# module::dir in the SOURCE_DIR list e.g.
#
# SOURCE_DIRS = ... module_xmos_xtcp::xtcp_apps/mdns ...
#

SOURCE_DIRS  = ...             

# The INCLUDE_DIRS variable lists all the directories added to the include 
# search path when building.

INCLUDE_DIRS = ...

# All libraries found in the directories listed in the LIB_DIRS variable
# will be linked into the build.

LIB_DIRS = ...

# The flags passed to xcc when building the application

XCC_FLAGS = ...

# The USED_MODULES variable lists other module used by the application. These
# modules will extend the SOURCE_DIRS, INCLUDE_DIRS and LIB_DIRS variables. 
# Modules are expected to be in the directory above the BASE_DIR directory.

USED_MODULES = ...

# The final target of the build. This is usually dependent on a binary file
# in the $(BIN_DIR) directory e.g.
#
#  all : $(BIN_DIR)/my_app.xe

all: ...

# You can change the flags of a set of files using the SET_XCC_[lang]_FLAGS
# functions. The first argument is a list of directories and the
# second argument is the value to set the compile flags to. e.g.
#
# $(call SET_XCC_C_FLAGS, mydir1 mydir2, $(XCC_FLAGS) -g -O3)


# You can change the flags of an individual file by setting the 
# XCC_FLAGS_[filename] variable. e.g.
#
# XCC_FLAGS_myfile.xc = $(XCC_FLAGS) -fsubword-select


# You can exclude particular files from the build even if they occur
# within SOURCE_DIRS by adding the file name (with no path) to the 
# EXCLUDE_FILES variable e..g
#
# EXCLUDE_FILES += myfile.xc
#


# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit this apart from
# changing the version of module_xmos_common.

include $(BASE_DIR)/../module_xmos_common.1v0/build/Makefile.common

clean: clean_common